export const sampleJobData = [
  {
    _id: 2702202320050001,
    companyName: "TCS",
    position: "Full Stack Developer",
    positionType: "Internship",
    salary: 10000,
    src: "https://companieslogo.com/img/orig/TCS.NS-7401f1bd.png?t=1631949260",
    startDate: "Immediately",
    applyBy: "28 Feb, 2023",
    duration: "6 Months",
    location: "W.F.H",
    roles: [
      "Creating REST APIs using Node.js and express Framework, designing DB schema for given applications in MySQL (mandatory).",
      "Working extensively around MYSQL queries and optimization of application performance",
      "Ensuring responsiveness to front-end requests",
      "Collaborating with front-end developers on the integration of elements",
      "Keeping informed of advancements in the field of Node.js development",
    ],
    skillsRequired: ["ReactJs", "NodeJs", "ExpressJs", "MongoDb", "MySQL"],
    perks: ["5 days a week"],
  },
  {
    _id: 2702202320050002,
    companyName: "OYO",
    position: "Digital Marketing",
    positionType: "Internship",
    salary: 7500,
    src: "https://upload.wikimedia.org/wikipedia/commons/1/19/OYO_Rooms_%28logo%29.png",
    startDate: "March, 2023",
    applyBy: "31 Mar, 2023, ",
    duration: "3 Months",
    location: "Remote",
    roles: [
      "Creating REST APIs using Node.js and express Framework, designing DB schema for given applications in MySQL (mandatory).",
      "Working extensively around MYSQL queries and optimization of application performance",
      "Ensuring responsiveness to front-end requests",
      "Collaborating with front-end developers on the integration of elements",
    ],
    skillsRequired: ["ReactJs", "NodeJs", "ExpressJs", "MongoDb"],
    perks: ["5 days a week", "Job Offer"],
    additionalInformation:
      "Job offer will be decided on the basis of Performance during the internship/probation period.",
  },
  {
    _id: 2702202320050003,
    companyName: "Apple Inc.",
    position: "Software Engineer",
    positionType: "Full-time Job",
    salary: 25000,
    src: "https://static.vecteezy.com/system/resources/thumbnails/002/520/838/small/apple-logo-black-isolated-on-transparent-background-free-vector.jpg",
    startDate: "Immediately",
    applyBy: "05 Mar, 2023",
    duration: "2 Years",
    location: "W.F.O",
    roles: [
      "Creating REST APIs using Node.js and express Framework, designing DB schema for given applications in MySQL (mandatory).",
      "Working extensively around MYSQL queries and optimization of application performance",
    ],
    skillsRequired: [
      "ReactJs",
      "NodeJs",
      "ExpressJs",
      "MongoDb",
      "MySQL",
      "Java",
      "DSA",
    ],
    perks: ["5 days a week", "Job Offer", "Flexible Timing"],
    additionalInformation:
      "Job offer will be decided on the basis of Performance during the internship/probation period.",
  },
];

export const sampleCandidateData = [
  {
    _id: 1,
    src: "https://i.kym-cdn.com/entries/icons/original/000/018/385/Rs_634x1024-130605092844-634.DespMe2.mh.060513.jpg",
    candidateName: "Kamal Sharma",
    highestQualification: "B.E in Computer Engineering",
    skills: [
      "MERN Stack",
      "MySQL",
      "QA Testing",
      "Data Analyst",
      "Computer Engineer",
    ],
  },
  {
    _id: 2,
    src: "https://i.kym-cdn.com/entries/icons/original/000/018/385/Rs_634x1024-130605092844-634.DespMe2.mh.060513.jpg",
    candidateName: "Avadhesh Sharma",
    highestQualification: "Diploma in Mechanical Engineering",
    skills: [
      "Radiography Testing",
      "RTL-2",
      "Mechanical Engineer",
      "PCN Level-2",
    ],
  },
];
